# Generated by Django 2.2.2 on 2022-02-14 11:00

from django.db import migrations, models
import namastenepal.chat_messages.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUsersGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('latest_activity', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatUsersGroupProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed Group', max_length=20)),
                ('icon_width', models.IntegerField(default=0)),
                ('icon_height', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, height_field='icon_height', null=True, upload_to=namastenepal.chat_messages.models.get_group_icon_path, width_field='icon_width')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=namastenepal.chat_messages.models.get_message_attachment_path)),
                ('content', models.TextField(null=True)),
                ('seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
