# Generated by Django 2.2.2 on 2022-02-14 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('community', '0002_auto_20220214_1645'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('p', 'Post'), ('c', 'Comment'), ('s', 'Community'), ('f', 'Friend')], max_length=1, null=True)),
                ('action', models.CharField(max_length=255)),
                ('seen', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('t', 'Tag'), ('l', 'Like'), ('s', 'Suggestion'), ('r', 'Removed')], default='l', max_length=1)),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_notification', to='notifications.Notification')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_notifications', to='posts.Post')),
            ],
        ),
        migrations.CreateModel(
            name='FriendNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('r', 'Request Accept')], default='r', max_length=1)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_notifications', to=settings.AUTH_USER_MODEL)),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friend_notification', to='notifications.Notification')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('j', 'Join Request'), ('r', 'Request Accept')], default='r', max_length=1)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_notifications', to='community.Community')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_notification', to='notifications.Notification')),
            ],
        ),
        migrations.CreateModel(
            name='CommentNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('c', 'Tag'), ('r', 'Reply'), ('m', 'Mention'), ('u', 'Upvote')], default='c', max_length=1)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_notifications', to='posts.Comment')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment_notification', to='notifications.Notification')),
            ],
        ),
    ]
